### ISSUE TITLE
Cannot export after updating to newer version

### ISSUE THREAD

**Issue by gracie95** [cyb3rko/pincredible#15]
After updating to latest version (0.4.1), tried to export and I faced this error message

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	... 1 more
Caused by: java.io.InvalidClassException: com.cyb3rko.pincredible.data.PinTable; local class incompatible: stream classdesc serialVersionUID = -1884388637003576280, local class serialVersionUID = 5997637778385570065
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:624)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1713)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1594)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1872)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1412)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
	at com.cyb3rko.pincredible.utils.ObjectSerializer.deserialize(Unknown Source:15)
	at com.cyb3rko.pincredible.utils.BackupHandler.runExport(SourceFile:151)
	at com.cyb3rko.pincredible.utils.BackupHandler.access$runExport(Unknown Source:0)
	at com.cyb3rko.pincredible.utils.BackupHandler$runBackup$1.invoke(Unknown Source:81)
	at com.cyb3rko.pincredible.utils.BackupHandler$runBackup$1.invoke(Unknown Source:6)
	at com.cyb3rko.pincredible.modals.PasswordDialog.show$lambda$1$lambda$0(Unknown Source:40)
	at com.cyb3rko.pincredible.modals.PasswordDialog.b(Unknown Source:0)
	at m1.e.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:7870)
	at android.widget.TextView.performClick(TextView.java:14970)
	at com.google.android.material.button.MaterialButton.performClick(SourceFile:10)
	at android.view.View.performClickInternal(View.java:7839)
	at android.view.View.access$3600(View.java:886)
	at android.view.View$PerformClick.run(View.java:29363)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	... 3 more
```

**Comment by cyb3rko** [comment]
Should be fixed from [Version 0.4.2](https://github.com/cyb3rko/pincredible/releases/tag/v0.4.2) and newer.  
Note the Breaking Changes!
