### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by hjek** [cyb3rko/pincredible#31]
Crash on open. App displays this:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cyb3rko.pincredible/com.cyb3rko.pincredible.MainActivity}: ir: Unable to instantiate fragment y50: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3751)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3888)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5888)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5769)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:72)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:137)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2374)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8046)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
Caused by: ir: Unable to instantiate fragment y50: could not find Fragment constructor
	at yr.a(SourceFile:59)
	at rs.a(SourceFile:3)
	at androidx.fragment.app.a.<init>(SourceFile:13)
	at fs.X(SourceFile:258)
	at fs.b(SourceFile:168)
	at cf.a(SourceFile:156)
	at androidx.activity.a.onCreate(SourceFile:31)
	at nr.onCreate(SourceFile:1)
	at r9.onCreate(SourceFile:10)
	at com.cyb3rko.pincredible.MainActivity.onCreate(SourceFile:1)
	at android.app.Activity.performCreate(Activity.java:8328)
	at android.app.Activity.performCreate(Activity.java:8307)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1386)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3731)
	... 15 more
Caused by: java.lang.NoSuchMethodException: y50.<init> []
	at java.lang.Class.getConstructor0(Class.java:2363)
	at java.lang.Class.getConstructor(Class.java:1759)
	at yr.a(SourceFile:24)
	... 28 more
```

**Comment by hjek** [comment]
android 13  
motorola e13
